[2024-06-01T03:14:38.739+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T03:14:38.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soc_domain_analysis.domain_analysis manual__2024-06-01T03:14:37.843768+00:00 [queued]>
[2024-06-01T03:14:38.753+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soc_domain_analysis.domain_analysis manual__2024-06-01T03:14:37.843768+00:00 [queued]>
[2024-06-01T03:14:38.753+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-01T03:14:38.757+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): domain_analysis> on 2024-06-01 03:14:37.843768+00:00
[2024-06-01T03:14:38.760+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=323) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T03:14:38.760+0000] {standard_task_runner.py:63} INFO - Started process 324 to run task
[2024-06-01T03:14:38.760+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'soc_domain_analysis', 'domain_analysis', 'manual__2024-06-01T03:14:37.843768+00:00', '--job-id', '3672', '--raw', '--subdir', 'DAGS_FOLDER/soc_dag.py', '--cfg-path', '/tmp/tmp1bi7013l']
[2024-06-01T03:14:38.761+0000] {standard_task_runner.py:91} INFO - Job 3672: Subtask domain_analysis
[2024-06-01T03:14:38.767+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T03:14:38.778+0000] {task_command.py:426} INFO - Running <TaskInstance: soc_domain_analysis.domain_analysis manual__2024-06-01T03:14:37.843768+00:00 [running]> on host a38c259dd974
[2024-06-01T03:14:38.806+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soc_domain_analysis' AIRFLOW_CTX_TASK_ID='domain_analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T03:14:37.843768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T03:14:37.843768+00:00'
[2024-06-01T03:14:38.806+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T03:14:38.811+0000] {soc_dag.py:28} INFO - Starting to fetch soc
[2024-06-01T03:14:38.811+0000] {soc_dag.py:35} ERROR - Error fetching domains: module 'datetime' has no attribute 'now'
[2024-06-01T03:14:38.811+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T03:14:38.812+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/soc_dag.py", line 29, in domain_analysis
    result = DomainAnalysisOperator.query_domain("google.com")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/analysis.py", line 161, in query_domain
    domain_creation_date = datetime.now()
                           ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
[2024-06-01T03:14:38.816+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=soc_domain_analysis, task_id=domain_analysis, run_id=manual__2024-06-01T03:14:37.843768+00:00, execution_date=20240601T031437, start_date=20240601T031438, end_date=20240601T031438
[2024-06-01T03:14:38.819+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3672 for task domain_analysis (module 'datetime' has no attribute 'now'; 324)
[2024-06-01T03:14:38.865+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T03:14:38.872+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T03:14:38.873+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
