[2024-05-28T23:33:05.412+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T23:33:05.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soc_domain_analysis.domain_analysis manual__2024-05-28T23:32:41.858857+00:00 [queued]>
[2024-05-28T23:33:05.426+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soc_domain_analysis.domain_analysis manual__2024-05-28T23:32:41.858857+00:00 [queued]>
[2024-05-28T23:33:05.426+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-28T23:33:05.430+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): domain_analysis> on 2024-05-28 23:32:41.858857+00:00
[2024-05-28T23:33:05.432+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=897) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-28T23:33:05.433+0000] {standard_task_runner.py:63} INFO - Started process 898 to run task
[2024-05-28T23:33:05.432+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'soc_domain_analysis', 'domain_analysis', 'manual__2024-05-28T23:32:41.858857+00:00', '--job-id', '3625', '--raw', '--subdir', 'DAGS_FOLDER/soc_dag.py', '--cfg-path', '/tmp/tmpvbwx9x9a']
[2024-05-28T23:33:05.433+0000] {standard_task_runner.py:91} INFO - Job 3625: Subtask domain_analysis
[2024-05-28T23:33:05.439+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-28T23:33:05.451+0000] {task_command.py:426} INFO - Running <TaskInstance: soc_domain_analysis.domain_analysis manual__2024-05-28T23:32:41.858857+00:00 [running]> on host b08e48600157
[2024-05-28T23:33:05.478+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soc_domain_analysis' AIRFLOW_CTX_TASK_ID='domain_analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T23:32:41.858857+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T23:32:41.858857+00:00'
[2024-05-28T23:33:05.478+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T23:33:05.483+0000] {soc_dag.py:28} INFO - Starting to fetch soc
[2024-05-28T23:33:05.483+0000] {soc_dag.py:35} ERROR - Error fetching domains: name 'get_domain_creation_date' is not defined
[2024-05-28T23:33:05.483+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T23:33:05.483+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/soc_dag.py", line 29, in domain_analysis
    result = DomainAnalysisOperator.query_domain("google.com")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/analysis.py", line 161, in query_domain
    domain_creation_date = get_domain_creation_date(domain)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'get_domain_creation_date' is not defined
[2024-05-28T23:33:05.488+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=soc_domain_analysis, task_id=domain_analysis, run_id=manual__2024-05-28T23:32:41.858857+00:00, execution_date=20240528T233241, start_date=20240528T233305, end_date=20240528T233305
[2024-05-28T23:33:05.492+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3625 for task domain_analysis (name 'get_domain_creation_date' is not defined; 898)
[2024-05-28T23:33:05.534+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T23:33:05.541+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T23:33:05.542+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
