[2024-05-28T22:20:22.182+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T22:20:22.194+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soc_domain_analysis.domain_analysis manual__2024-05-28T22:20:21.628450+00:00 [queued]>
[2024-05-28T22:20:22.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soc_domain_analysis.domain_analysis manual__2024-05-28T22:20:21.628450+00:00 [queued]>
[2024-05-28T22:20:22.197+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-28T22:20:22.202+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): domain_analysis> on 2024-05-28 22:20:21.628450+00:00
[2024-05-28T22:20:22.204+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-28T22:20:22.204+0000] {standard_task_runner.py:63} INFO - Started process 743 to run task
[2024-05-28T22:20:22.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'soc_domain_analysis', 'domain_analysis', 'manual__2024-05-28T22:20:21.628450+00:00', '--job-id', '3612', '--raw', '--subdir', 'DAGS_FOLDER/soc_dag.py', '--cfg-path', '/tmp/tmp6ahtmflh']
[2024-05-28T22:20:22.205+0000] {standard_task_runner.py:91} INFO - Job 3612: Subtask domain_analysis
[2024-05-28T22:20:22.210+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-28T22:20:22.223+0000] {task_command.py:426} INFO - Running <TaskInstance: soc_domain_analysis.domain_analysis manual__2024-05-28T22:20:21.628450+00:00 [running]> on host 5548bb52b807
[2024-05-28T22:20:22.252+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soc_domain_analysis' AIRFLOW_CTX_TASK_ID='domain_analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T22:20:21.628450+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T22:20:21.628450+00:00'
[2024-05-28T22:20:22.253+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T22:20:22.261+0000] {soc_dag.py:22} INFO - Starting to fetch soc
[2024-05-28T22:20:22.261+0000] {soc_dag.py:28} ERROR - Error fetching domains: name 'Null' is not defined
[2024-05-28T22:20:22.261+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T22:20:22.262+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/soc_dag.py", line 26, in domain_analysis
    return Null
           ^^^^
NameError: name 'Null' is not defined
[2024-05-28T22:20:22.268+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=soc_domain_analysis, task_id=domain_analysis, run_id=manual__2024-05-28T22:20:21.628450+00:00, execution_date=20240528T222021, start_date=20240528T222022, end_date=20240528T222022
[2024-05-28T22:20:22.273+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3612 for task domain_analysis (name 'Null' is not defined; 743)
[2024-05-28T22:20:22.314+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T22:20:22.321+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T22:20:22.322+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
