[2024-06-01T06:39:24.993+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T06:39:25.003+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soc_domain_analysis_procedural.fetch_analyze_persist_task scheduled__2023-01-02T05:00:00+00:00 [queued]>
[2024-06-01T06:39:25.006+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soc_domain_analysis_procedural.fetch_analyze_persist_task scheduled__2023-01-02T05:00:00+00:00 [queued]>
[2024-06-01T06:39:25.006+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-01T06:39:25.010+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_analyze_persist_task> on 2023-01-02 05:00:00+00:00
[2024-06-01T06:39:25.012+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1337) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T06:39:25.013+0000] {standard_task_runner.py:63} INFO - Started process 1338 to run task
[2024-06-01T06:39:25.012+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'soc_domain_analysis_procedural', 'fetch_analyze_persist_task', 'scheduled__2023-01-02T05:00:00+00:00', '--job-id', '3784', '--raw', '--subdir', 'DAGS_FOLDER/asset_analysis_procedural.py', '--cfg-path', '/tmp/tmp7vq53m4t']
[2024-06-01T06:39:25.013+0000] {standard_task_runner.py:91} INFO - Job 3784: Subtask fetch_analyze_persist_task
[2024-06-01T06:39:25.019+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T06:39:25.031+0000] {task_command.py:426} INFO - Running <TaskInstance: soc_domain_analysis_procedural.fetch_analyze_persist_task scheduled__2023-01-02T05:00:00+00:00 [running]> on host 328411755fd7
[2024-06-01T06:39:25.063+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soc_domain_analysis_procedural' AIRFLOW_CTX_TASK_ID='fetch_analyze_persist_task' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T05:00:00+00:00'
[2024-06-01T06:39:25.063+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T06:39:25.069+0000] {asset_analysis_procedural.py:27} INFO - Starting to fetch domains
[2024-06-01T06:39:25.087+0000] {asset_analysis_procedural.py:43} INFO - Fetched domains
[2024-06-01T06:39:25.087+0000] {asset_analysis_procedural.py:47} INFO - Analyzing domain: goggle.com with original domain: google.com
[2024-06-01T06:39:25.375+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-06-01T06:39:25.396+0000] {process_utils.py:132} INFO - Sending 15 to group 1338. PIDs of all processes in the group: [1338]
[2024-06-01T06:39:25.414+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1338
[2024-06-01T06:39:25.429+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-01T06:39:25.430+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T06:39:25.446+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/asset_analysis_procedural.py", line 48, in fetch_analyze_persist_domains
    result = DomainAnalysisOperator.compare_urls(original_domain, domain_result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/analysis.py", line 260, in compare_urls
    result_old = DomainAnalysisOperator.get_favicon_hash(domain_old)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/analysis.py", line 32, in get_favicon_hash
    favicon_response = requests.get(f"{full_url}/favicon.ico", timeout=5)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 759, in _ssl_wrap_socket_and_match_hostname
    context = create_urllib3_context(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 285, in create_urllib3_context
    context = SSLContext(PROTOCOL_TLS_CLIENT)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 438, in __new__
    self = _SSLContext.__new__(cls, protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-01T06:39:25.455+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=soc_domain_analysis_procedural, task_id=fetch_analyze_persist_task, run_id=scheduled__2023-01-02T05:00:00+00:00, execution_date=20230102T050000, start_date=20240601T063925, end_date=20240601T063925
[2024-06-01T06:39:25.480+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1338, status='terminated', exitcode=2, started='06:39:24') (1338) terminated with exit code 2
[2024-06-01T06:39:25.481+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2024-06-01T06:39:25.506+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
