[2024-05-20T12:19:22.377+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T12:19:22.392+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: domain_analysis_full.fetch_and_analyze_domains scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-05-20T12:19:22.395+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: domain_analysis_full.fetch_and_analyze_domains scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-05-20T12:19:22.395+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-20T12:19:22.403+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_analyze_domains> on 2023-01-01 00:00:00+00:00
[2024-05-20T12:19:22.408+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=491) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-20T12:19:22.407+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'domain_analysis_full', 'fetch_and_analyze_domains', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '1485', '--raw', '--subdir', 'DAGS_FOLDER/analysis_test_dag.py', '--cfg-path', '/tmp/tmp26g91fnn']
[2024-05-20T12:19:22.408+0000] {standard_task_runner.py:63} INFO - Started process 492 to run task
[2024-05-20T12:19:22.409+0000] {standard_task_runner.py:91} INFO - Job 1485: Subtask fetch_and_analyze_domains
[2024-05-20T12:19:22.416+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-20T12:19:22.434+0000] {task_command.py:426} INFO - Running <TaskInstance: domain_analysis_full.fetch_and_analyze_domains scheduled__2023-01-01T00:00:00+00:00 [running]> on host 667df64f43b9
[2024-05-20T12:19:22.470+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='domain_analysis_full' AIRFLOW_CTX_TASK_ID='fetch_and_analyze_domains' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2024-05-20T12:19:22.470+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T12:19:22.477+0000] {analysis_test_dag.py:32} INFO - Starting to fetch domains
[2024-05-20T12:19:22.491+0000] {analysis_test_dag.py:50} ERROR - Error fetching and analyzing domains: name 'engine' is not defined
[2024-05-20T12:19:22.491+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T12:19:22.492+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/analysis_test_dag.py", line 44, in fetch_and_analyze_domains
    analyze_domain(session, metadata, domain)
  File "/opt/airflow/dags/analysis_test_dag.py", line 58, in analyze_domain
    domain_analysis = Table('domain_analysis', metadata, autoload_with=engine, schema='analysis')
                                                                       ^^^^^^
NameError: name 'engine' is not defined
[2024-05-20T12:19:22.497+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=domain_analysis_full, task_id=fetch_and_analyze_domains, run_id=scheduled__2023-01-01T00:00:00+00:00, execution_date=20230101T000000, start_date=20240520T121922, end_date=20240520T121922
[2024-05-20T12:19:22.500+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1485 for task fetch_and_analyze_domains (name 'engine' is not defined; 492)
[2024-05-20T12:19:22.513+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T12:19:22.520+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T12:19:22.520+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
