[2024-06-01T06:38:22.475+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T06:38:22.486+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soc_domain_analysis_procedural.fetch_analyze_persist_task manual__2024-06-01T06:37:30.107316+00:00 [queued]>
[2024-06-01T06:38:22.488+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soc_domain_analysis_procedural.fetch_analyze_persist_task manual__2024-06-01T06:37:30.107316+00:00 [queued]>
[2024-06-01T06:38:22.488+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-01T06:38:22.492+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_analyze_persist_task> on 2024-06-01 06:37:30.107316+00:00
[2024-06-01T06:38:22.495+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1240) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T06:38:22.495+0000] {standard_task_runner.py:63} INFO - Started process 1241 to run task
[2024-06-01T06:38:22.495+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'soc_domain_analysis_procedural', 'fetch_analyze_persist_task', 'manual__2024-06-01T06:37:30.107316+00:00', '--job-id', '3768', '--raw', '--subdir', 'DAGS_FOLDER/asset_analysis_procedural.py', '--cfg-path', '/tmp/tmpy_u1rq09']
[2024-06-01T06:38:22.496+0000] {standard_task_runner.py:91} INFO - Job 3768: Subtask fetch_analyze_persist_task
[2024-06-01T06:38:22.502+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T06:38:22.513+0000] {task_command.py:426} INFO - Running <TaskInstance: soc_domain_analysis_procedural.fetch_analyze_persist_task manual__2024-06-01T06:37:30.107316+00:00 [running]> on host 328411755fd7
[2024-06-01T06:38:22.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soc_domain_analysis_procedural' AIRFLOW_CTX_TASK_ID='fetch_analyze_persist_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T06:37:30.107316+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T06:37:30.107316+00:00'
[2024-06-01T06:38:22.543+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T06:38:22.548+0000] {asset_analysis_procedural.py:27} INFO - Starting to fetch domains
[2024-06-01T06:38:22.565+0000] {asset_analysis_procedural.py:43} INFO - Fetched domains
[2024-06-01T06:38:22.565+0000] {asset_analysis_procedural.py:47} INFO - Analyzing domain: goggle.com with original domain: google.com
[2024-06-01T06:38:23.536+0000] {asset_analysis_procedural.py:50} INFO - Persisting domain analysis for: goggle.com
[2024-06-01T06:38:23.538+0000] {asset_analysis_procedural.py:76} ERROR - Error fetching, analyzing, or persisting domains: name 'url' is not defined
[2024-06-01T06:38:23.539+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T06:38:23.540+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/asset_analysis_procedural.py", line 63, in fetch_analyze_persist_domains
    logging.info(f"Persisting URL analysis for: {url}")
                                                 ^^^
NameError: name 'url' is not defined
[2024-06-01T06:38:23.551+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=soc_domain_analysis_procedural, task_id=fetch_analyze_persist_task, run_id=manual__2024-06-01T06:37:30.107316+00:00, execution_date=20240601T063730, start_date=20240601T063822, end_date=20240601T063823
[2024-06-01T06:38:23.558+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3768 for task fetch_analyze_persist_task (name 'url' is not defined; 1241)
[2024-06-01T06:38:23.597+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T06:38:23.608+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T06:38:23.609+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
